worker_processes 1;
events { worker_connections 1024; }

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    server {
        listen       8080;                  # 必须改成 8080
        server_name  localhost;
        client_max_body_size 10m;
        
        location / {
            root   /usr/share/nginx/html;   # 绝对路径
            index  index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        location ^~ /api/ {
            rewrite ^/api/(.*)$ /$1 break;
            # 注意：后端地址必须准确，且建议加一个防止跨域的主机头
            proxy_pass https://sky-take-out666-production.up.railway.app;
            proxy_set_header Host sky-take-out666-production.up.railway.app;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }
}