http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    server {
        listen       80;  # 改成 80，Docker 容器默认端口
        server_name  localhost;
        client_max_body_size 10m;
        
        location / {
            root   html;
            index  index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        location ^~ /api/ {
            rewrite ^/api/(.*)$ /$1 break;
            # 重点：把下面的地址换成你 Railway 上 Java 后端的公网域名
            proxy_pass https://sky-take-out666-production.up.railway.app;
            # 补充必要的代理请求头
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }
}