worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    map $http_upgrade $connection_upgrade{
        default upgrade;
        '' close;
    }

    server {
        listen       8080;                  # 【修改1】必须改成 8080
        server_name  localhost;
        client_max_body_size 10m;

        location / {
            root   /usr/share/nginx/html/sky;    # 【修改2】云端绝对路径
            index  index.html index.htm;
            try_files $uri $uri/ /index.html; # 【修改3】解决刷新404
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html/sky;
        }

        # 反向代理,处理管理端发送的请求
        location /api/ {
            # 【修改4】将下面的地址换成你 Railway 后端的公网地址，注意末尾的 /admin/
            proxy_pass https://sky-take-out666-production.up.railway.app/admin/;
            proxy_set_header Host sky-take-out666-production.up.railway.app;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        
        # 反向代理,处理用户端发送的请求
        location /user/ {
            # 【修改5】同样换成你的后端地址
            proxy_pass https://sky-take-out666-production.up.railway.app/user/;
            proxy_set_header Host sky-take-out666-production.up.railway.app;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        
        # WebSocket
        location /ws/ {
            proxy_pass https://sky-take-out666-production.up.railway.app/ws/;
            proxy_http_version 1.1;
            proxy_read_timeout 3600s;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "$connection_upgrade";
            proxy_set_header Host sky-take-out666-production.up.railway.app;
        }
    }
}